###

POST https://localhost:7019/api/product
Content-Type: application/json

{
    "product_name": "Tenis Adidas",
    "product_image": "",
    "product_desc": "Tenis superstar adidas, mega confortavel, tenis original, para corrida, caminhadas e casual.",
    "inventory": 10,
    "status": true,
    "price": 129.99
}

###

GET https://localhost:7019/api/product/6ba6684a-6c55-4068-bc0c-119546b0bd2c

###

GET https://localhost:7019/api/product

###

PUT https://localhost:7019/api/product
Content-Type: application/json

{
    "product_name": "nome do produto alterado",
    "product_image": "a",
    "product_desc": "desc",
    "inventory": 90,
    "status": true,
    "price": 129.99
}

###

DELETE https://localhost:7019/api/product/aa87843a-d7bb-443b-a8a7-30c9a686fd28